# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end

  config.vm.define :router do |router|
    router.vm.box = "chef/centos-6.5"
    router.vm.network "private_network", ip: "10.0.0.2"
    router.vm.network "private_network", ip: "10.0.0.10"
  end

  config.vm.define :hostA do |router|
    router.vm.box = "chef/centos-6.5"
    router.vm.network "private_network", ip: "10.0.0.20"
  end

  config.vm.define :hostB do |router|
    router.vm.box = "chef/centos-6.5"
    router.vm.network "private_network", ip: "10.0.0.21"
  end

end
