# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # config.vm.box = "."
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    #vb.memory = "2048"
  end

  config.vm.define :ubuntu_trusty64 do |desktop|
    desktop.vm.box = "ubuntu/trusty64"
  end

  config.vm.define :ubuntu1504_desktop do |desktop|
    desktop.vm.box = "ninthport/ubuntu1504-desktop"
    desktop.vm.synced_folder "../data/projects", "/projects"
  end

  config.vm.define :centos_65 do |desktop|
    desktop.vm.box = "chef/centos-6.5"
  end

  config.vm.define :centos_70 do |desktop|
    desktop.vm.box = "chef/centos-7.0"
  end

end
