# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # config.vm.box = "."
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  config.vm.synced_folder "../../training", "/training"
  config.vm.synced_folder "../../work/", "/work"
  config.vm.synced_folder "../../work/gap/gap-corp", "/chef"

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  config.vm.provision "shell", inline: <<-SHELL
    # sudo yum update -y
    # sudo yum install chefdk
  SHELL

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  config.vm.define :u15 do |desktop|
    desktop.vm.box = "ninthport/ubuntu1504-desktop"
  desktop.vm.synced_folder "../data/projects", "/projects"
  end

  config.vm.define :c65 do |desktop|
    desktop.vm.box = "chef/centos-6.5"
  end

  config.vm.define :c70 do |desktop|
    desktop.vm.box = "chef/centos-7.0"
  end

end
